theme: jekyll-theme-minimal
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
title: Schen1025's homepage
description: Bookmark this to keep an eye on my fall 2024 digital humanities portfolio!
